  # Etape de build avec Maven
  FROM maven:3.6.0-jdk-11 as builder

  WORKDIR /app

  # Copie du fichier pom.xml et téléchargement des dépendances
  COPY server/payment-service/pom.xml .
  RUN mvn dependency:go-offline

  # Copie des fichiers sources et exécution de la construction
  COPY server/payment-service/src ./src
  RUN mvn package -DskipTests


  FROM openjdk:11

  WORKDIR /app

  # Copie de l'artifact JAR depuis l'étape précédente
  COPY --from=builder /app/target/payment-service.jar .

  EXPOSE 9050

  # Exécution de l'application Spring Boot
  ENTRYPOINT ["java", "-jar", "payment-service.jar"]


