  FROM maven:3.6.0-jdk-11 as builder

  WORKDIR /app

  COPY server/payment-service/pom.xml .
  RUN mvn dependency:go-offline

  COPY server/payment-service/src ./src
  RUN mvn package -DskipTests


  FROM openjdk:11

  WORKDIR /app

  COPY --from=builder /app/target/payment-service.jar .

  EXPOSE 9050

  ENTRYPOINT ["java", "-jar", "payment-service.jar"]


