FROM maven:3.6.0-jdk-11 as builder

WORKDIR /app

COPY server/common-data-service/pom.xml .
RUN mvn dependency:go-offline

COPY server/common-data-service/src ./src
RUN mvn package -DskipTests



FROM openjdk:11

WORKDIR /app


COPY --from=builder /app/target/common-data-service.jar .

EXPOSE 9000

ENTRYPOINT ["java", "-jar", "common-data-service.jar"]


