FROM maven:3.6.0-jdk-11 as builder

WORKDIR /app

COPY server/authentication-service/pom.xml .
RUN mvn dependency:go-offline

COPY server/authentication-service/src ./src
RUN mvn package -DskipTests



FROM openjdk:11

WORKDIR /app

COPY --from=builder /app/target/authentication-service.jar .

EXPOSE 7000

ENTRYPOINT ["java", "-jar", "authentication-service.jar"]
