  FROM maven as builder

  WORKDIR /app

  COPY server/search-service/pom.xml .
  RUN mvn dependency:go-offline

  COPY server/search-service/src ./src
  RUN mvn package -DskipTests


  FROM openjdk:17

  WORKDIR /app

  COPY --from=builder /app/target/search-service-0.0.1-SNAPSHOT.jar .

  EXPOSE 10000

  ENTRYPOINT ["java", "-jar", "search-service-0.0.1-SNAPSHOT.jar"]


